import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";

import Header from "@/components/header";

import "./globals.css";
import Footer from "@/components/footer";
import FloatWhatsapp from "@/components/floatWhatsapp";
import { FirebaseAnalytics } from "@/context";

const inter = Inter({ subsets: ["latin"], variable: '--font-inter' });
const montserrat = Montserrat({ subsets: ["latin"], variable: '--font-montserrat', display: 'swap', });

export const metadata: Metadata = {
  title: "MedicAll Farma",
  description: "Generated by create next app",
};



async function getData() {
  return 
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const contact_link = await getData()

  return (
    <html lang="pt-br">
      <body className={`${inter.className} ${montserrat.variable}`}>
        <Header />
        <FirebaseAnalytics>
          <div className="children">
            {children}
          </div>
          
          <FloatWhatsapp /> 
          <Footer />
        </FirebaseAnalytics>
      </body>
    </html>
  );
}
